### PR TITLE
Mask

### PR DESCRIPTION
**Pull request by edbentley**
This adds the ability to apply a mask to Sprites through a `mask` prop. See [mask.md](https://github.com/edbentley/replay/blob/mask/website/docs/mask.md) for examples.

### CODE REVIEW

**Comment by edbentley** [comment]
@ejb Curious to hear your feedback on this API.

**Comment by ejb** [comment]
This is a great start. Working well for rectangles and images, but I couldn't get it to work on a custom sprite.

I'd also love the ability to:

* Define curves rather than just straight lines (would be nice to have this as a plain ol' texture too)
* Use a bitmap image with transparency to define the mask (which has the added bonus of making fades possible)

**Comment by ejb** [comment]
For debugging purposes, here's the sprite that didn't work correctly:

[mask-test.txt](https://github.com/edbentley/replay/files/4957575/mask-test.txt)

**Comment by edbentley** [comment]
> I'd also love the ability to:

No reason they can't be added later on, I'm very open to follow-up PRs. 😉 

> For debugging purposes, here's the sprite that didn't work correctly:

If you replace `Pattern` with this, I think it's what you're after:

```js
export const Pattern = makeSprite({
  init() {
    return { offsetX: 0 };
  },
  loop({ state }) {
    return { offsetX: state.offsetX + 1 };
  },
  render({ props, state }) {
    // Need to remove mask when spreading props
    const { mask, ...restProps } = props;

    const images = PatternImages({
      id: "PatternImages",
      ...restProps,
      x: state.offsetX % props.width,
    });

    return [images];
  },
});
```

**Comment by ejb** [comment]
Oh duh. I had a double mask going. No wonder it didn't work.

I think this is good to merge, then! 👍

**Pull request merged**
