### PR TITLE
Add rounded prop to line texture

### PR DESCRIPTION
**Pull request by edbentley**
Option for rounded line ends

### CODE REVIEW

**Comment by ejb** [comment]
Nice addition but I wonder if it’s too generic a property name? HTML canvas uses [a lineCap prop](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/lineCap).

**Comment by edbentley** [comment]
Hmm yeah, but I didn't see the need for both `"butt"` and `"square"`. How about if the prop is called `roundedEnds`?

**Comment by ejb** [comment]
I disagree, the difference between the two is subtle but important when implementing designs. It’s a standard feature of vector editor/markup.

**Comment by edbentley** [comment]
Convinced 👍

**Pull request merged**
